services:

  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - auth_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/auth_db
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      DEMO_ADMIN_EMAIL: ${DEMO_ADMIN_EMAIL}
      DEMO_ADMIN_USERNAME: ${DEMO_ADMIN_USERNAME}
      DEMO_ADMIN_PASSWORD: ${DEMO_ADMIN_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8001:8001"

volumes:
  auth_postgres_data:
